dataset:
  class: evaluation.datasets.PopqaDataset

model:
  class: evaluation.models.SimpleLLM
  kwargs:
    model_name_or_path: "Qwen/Qwen2.5-1.5B-Instruct"
    device: "cuda:0"
    use_chat_template: true

generation:
  do_sample: true
  temperature: 0.3
  max_new_tokens: 512

experiment:
  sample_count: 1
