dataset:
  class: evaluation.datasets.PopqaDataset
experiment:
  sample_count: 1
generation:
  max_new_tokens: 512
model:
  class: evaluation.models.PiscoModel
  kwargs:
    device: cuda:0
    model_name_or_path: naver/pisco-mistral
    trust_remote_code: true
