dataset:
  class: evaluation.datasets.PopqaDataset
  args:
    - "s_wiki_content"

model:
  class: evaluation.models.XRAGModel
  kwargs:
    device: "cuda:0"
    llm_name_or_path: "~/repos/xRAG/cache"
    retriever_name_or_path: "Salesforce/SFR-Embedding-Mistral"
    xrag_token: "[XRAG]"

metrics:
  - class: evaluation.metrics.AlignScoreMetric
    args:
      model: roberta-base
      batch_size: 32
      device: cpu
      ckpt_path: cache/align_score_checkpoint
      eval_mode: nli_sp

generation:
  do_sample: true
  temperature: 0.7
  max_new_tokens: 400

experiment:
  sample_count: 3
